tag-name = "v{{version}}"
tag-message = "Release {{version}}"

publish = false
push = true

pre-release-commit-message = "Release {{version}}"
post-release-commit-message = "Start next development iteration {{next_version}}"