name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-musl:
    name: Build MUSL Release Binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Install Rust target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Install musl tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build MUSL release binary
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Upload MUSL binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: musl-binary
          path: target/x86_64-unknown-linux-musl/release/fm

  build-windows:
    name: Build Windows Release Binary
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Install Rust target
        run: rustup target add x86_64-pc-windows-msvc

      - name: Build Windows release binary
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Upload Windows binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: target/x86_64-pc-windows-msvc/release/fm.exe
